### ISSUE TITLE
pip install fails Ubuntu/LM18

### ISSUE THREAD

**Issue by FeralBytes** [matham/ffpyplayer#23]
I know this is similiar but I want to point out that the error is in the setup.py file and fails consistently making it very difficult to support ffpyplayer on Android. Failed both with Buildozer and P4A setup.py. But pip installs from github directly; or at least it managed to once.
I did follow and complete: https://github.com/matham/ffpyplayer/blob/master/.travis.yml#L20

```
Collecting ffpyplayer (from -r requirements.txt (line 2))
  Using cached ffpyplayer-4.0.0.zip
    Complete output from command python setup.py egg_info:
    Selecting SDL2 out of (SDL, SDL2)
    Generating ffconfig.h
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-O_gExg/ffpyplayer/setup.py", line 220, in <module>
        with open(join('ffpyplayer', 'includes', 'ffconfig.h'), 'w') as f:
    IOError: [Errno 2] No such file or directory: 'ffpyplayer/includes/ffconfig.h'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-O_gExg/ffpyplayer/

```

**Comment by FeralBytes** [comment]
Further even though the install of : 
```sh
sudo apt-get update;
sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev python-dev;
mkdir ~/ffmpeg_sources;
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/ffmpeg_build/lib;

sudo apt-get -y install yasm;
cd ~/ffmpeg_sources;
wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz;
tar xzf yasm-1.3.0.tar.gz;
cd yasm-1.3.0;
./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin";
make;
make install;
make distclean;

sudo apt-get -y install libx264-dev;
cd ~/ffmpeg_sources;
wget http://download.videolan.org/pub/x264/snapshots/last_x264.tar.bz2;
tar xjf last_x264.tar.bz2;
cd x264-snapshot*;
PATH="$HOME/ffmpeg_build/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin" --enable-shared --extra-cflags="-fPIC";
PATH="$HOME/ffmpeg_build/bin:$PATH" make;
make install;
make distclean;

sudo apt-get -y install libmp3lame-dev;
sudo apt-get -y install nasm;
cd ~/ffmpeg_sources;
wget http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz;
tar xzf lame-3.99.5.tar.gz;
cd lame-3.99.5;
./configure --prefix="$HOME/ffmpeg_build" --enable-nasm --enable-shared;
make;
make install;
make distclean;

sudo apt-get -y install libass-dev libfreetype6-dev libtheora-dev libvorbis-dev;
cd ~/ffmpeg_sources;
wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2;
tar xjf ffmpeg-snapshot.tar.bz2;
cd ffmpeg;
PATH="$HOME/ffmpeg_build/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --extra-cflags="-I$HOME/ffmpeg_build/include -fPIC" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/ffmpeg_build/bin" --enable-gpl --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-shared;
PATH="$HOME/ffmpeg_build/bin:$PATH" make;
make install;
make distclean;
hash -r;

pip install --upgrade cython nose;
```
was successful; trying to use ffpyplayer results in:
```
ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```

**Comment by FeralBytes** [comment]
This was myfault. Be sure to install ffpyplayer after you have completed the installation script; not at the same time; or else you will get the segfaults. Simply uninstalling and re-installing fixed the problem.
