### ISSUE TITLE
Build issue on OSX

### ISSUE THREAD

**Issue by cbenhagen** [matham/ffpyplayer#6]
```
 Traceback (most recent call last):
   File "test.py", line 9, in <module>
     from ffpyplayer.player import MediaPlayer
   File "ffpyplayer/player.pyx", line 31, in init ffpyplayer.player (ffpyplayer/player.c:8146)
     from ffpyplayer.tools import loglevels, _initialize_ffmpeg
 ImportError: dlopen(/Users/ben/Projects/ffpyplayer/ffpyplayer/tools.so, 2): Symbol not found: _AVMediaTypeAudio
   Referenced from: /Users/ben/Projects/ffpyplayer/ffpyplayer/tools.so
   Expected in: flat namespace
  in /Users/ben/Projects/ffpyplayer/ffpyplayer/tools.so
```

This might not be a bug but rather me doing something wrong. The compete build and run log can be found here: http://pastebin.com/kX7rm49S

**Comment by matham** [comment]
Unfortunately, I cannot help you there because I don't use a mac.

**Comment by matham** [comment]
It may be worth a try to see if the problem went away in the recent updates. I also managed to use it on osx using brew: http://matham.github.io/ffpyplayer/installation.html#osx.
