### ISSUE TITLE
Build for Android - iOS: Could not find suitable distribution for Requirement.parse('cython')

### ISSUE THREAD

**Issue by Thong-Tran** [matham/ffpyplayer#61]
### Versions

* Python: 3.7.1
* OS: MacOS 10.13.6
* Kivy: 1.10.1
* FFPyplayer: 4.1.0

### Description

It check cython don't exist and exits. But I change it to `['cython'] if have_cython else []` it work again.

https://github.com/matham/ffpyplayer/blob/7252a5628500b50564a349d886252d7526fc6c42/setup.py#L341

### Logs

```log
[INFO    ] Running Shell: /Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/bin/python ('setup.py', 'build_ext', '-g') 
{'_env': {'HAS_SDL2': '1', 'LD': u'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'USE_SDL2_MIXER': '1', 'LDFLAGS': u'-arch x86_64 --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/lib -lsqlite3 -miphoneos-version-min=8.0', 'KIVYIOSROOT': '/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios', 'CC': '/var/folders/vx/ywrxzl3n27q09h2psqlq4xk80000gn/T/tmpqwsnuI -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/libffi -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/common/sdl2_mixer', 'OTHER_CFLAGS': '-I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/ffi -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/openssl -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/ffmpeg -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64', 'FFMPEG_LIB_DIR': u'/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/build/ffmpeg/x86_64/ffmpeg-2.6.3/dist/lib', 'ARM_LD': u'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld', 'OTHER_LDFLAGS': '-L/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/lib', 'FFMPEG_INCLUDE_DIR': '/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/ffmpeg', 'CXX': '/var/folders/vx/ywrxzl3n27q09h2psqlq4xk80000gn/T/tmpX4IHmn', 'AR': u'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar', 'SDL_INCLUDE_DIR': '/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/common/sdl2', 'CFLAGS': '-O3 -miphoneos-version-min=8.0 -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/ffi -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/openssl -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64/ffmpeg -I/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/include/x86_64 -Wno-implicit-function-declaration -fno-strict-aliasing', 'LDSHARED': '/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/tools/liblink', 'SDL_LIB_DIR': '/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/lib', 'ARCH': 'x86_64', 'IOSSDKROOT': u'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk'}, '_iter': True, '_out_bufsize': 1, '_err_to_out': True}
[DEBUG   ] Environ change has_sdl2 -> True
[DEBUG   ] Environ change use_sdl2_mixer -> True
[DEBUG   ] Generating ffconfig.h
[DEBUG   ] Generating ffconfig.pxi
[DEBUG   ] Download error on https://pypi.python.org/simple/cython/: unknown url type: https -- Some packages may not be found!
[DEBUG   ] Couldn't find index page for 'cython' (maybe misspelled?)
[DEBUG   ] Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
[DEBUG   ] No local packages or working download links found for cython
[DEBUG   ] Traceback (most recent call last):
[DEBUG   ]   File "setup.py", line 341, in <module>
[DEBUG   ]     setup_requires=['cython'])
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/distutils/core.py", line 108, in setup
[DEBUG   ]     _setup_distribution = dist = klass(attrs)
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools/dist.py", line 317, in __init__
[DEBUG   ]     self.fetch_build_eggs(attrs['setup_requires'])
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
[DEBUG   ]     replace_conflicting=True,
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
[DEBUG   ]     dist = best[req.key] = env.best_match(req, ws, installer)
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
[DEBUG   ]     return self.obtain(req, installer)
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
[DEBUG   ]     return installer(requirement)
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
[DEBUG   ]     return cmd.easy_install(req)
[DEBUG   ]   File "/Users/ivc/kivy/.buildozer/ios/platform/kivy-ios/dist/hostpython3/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 668, in easy_install
[DEBUG   ]     raise DistutilsError(msg)
[DEBUG   ] distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cython')
```

**Comment by matham** [comment]
It could be because `Cython` needs to be capitalized. But cython is a setup requirement so it shouldn't be removed.

**Comment by Thong-Tran** [comment]
But when I add this code, it build successful with no error. And If i add PYTHONPATH in recipe_env, it will show more errors like SyntaxError.
As far as I know, it is not necessary here because cythonize processing has been completely separated from compile code.

**Comment by matham** [comment]
This should work since people are using it on ios. If there are issues, the recipe there probably needs to be adjusted.
