### ISSUE TITLE
ffpyplayer.tools.list_dshow_devices AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by redstoneleo** [matham/ffpyplayer#70]
```
from ffpyplayer.tools import list_dshow_devices
print(list_dshow_devices())
```
gives:

```
Traceback (most recent call last):
  File "D:\Python\player.py", line 18, in <module>
    print(list_dshow_devices())
  File "ffpyplayer\tools.pyx", line 753, in ffpyplayer.tools.list_dshow_devices
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by matham** [comment]
Are you on Python 2 or 3?

**Comment by redstoneleo** [comment]
`Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32`
