### ISSUE TITLE
On shutdown with other errors

### ISSUE THREAD

**Issue by kuzeyron** [matham/ffpyplayer#76]
Good evening!
I found another issue. By using your demo app as ground. I'm having following errors.
The top errors you already know about. But those under it is new.
And as usual, take your time. I'm almost never in a hurry.

The call I was making came from my own library. But I'm not getting any errors from a basic Kivy app.

Edit: Looks differently in https://gist.github.com/kuzeyron/caba23a65ec06b1d348238518bcbc78b
But `Error in sys.excepthook:` doesn't seem to show up.
If you wonder if I'm using `print()`. Yes sometimes but left off normally.

```
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_19-09-08_5.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.0.dev0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.1.5'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event11
[INFO   ] [MTD         ] Read event from </dev/input/event11>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [MTD         ] </dev/input/event11> range position X is 1232 - 5710
[INFO   ] [MTD         ] </dev/input/event11> range position Y is 1156 - 4696
[INFO   ] [MTD         ] </dev/input/event11> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event11> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event11> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event11> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event11> rotation set to 0
[INFO   ] [Generated background colors] 40 RGBA colors
[INFO   ] [Generated text colors] 40 RGBA colors
[INFO   ] [Reversed colors] No
[INFO   ] [WindowSDL   ] exiting mainloop and closing.
[INFO   ] [Base        ] Leaving application in progress...
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 95, in ffpyplayer.player.core.read_thread_enter
  File "ffpyplayer/player/core.pyx", line 2231, in ffpyplayer.player.core.VideoState.read_thread
  File "ffpyplayer/player/core.pyx", line 2250, in ffpyplayer.player.core.VideoState.failed
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 135, in ffpyplayer.player.core.audio_thread_enter
  File "ffpyplayer/player/core.pyx", line 1047, in ffpyplayer.player.core.VideoState.audio_thread
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 115, in ffpyplayer.player.core.video_thread_enter
  File "ffpyplayer/player/core.pyx", line 1255, in ffpyplayer.player.core.VideoState.video_thread
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
```

**Comment by AndreMiras** [comment]
You should share the part where you create the `MediaPlayer` object. It feels like you're passing the constructor more parameters than you should

**Comment by matham** [comment]
I'm kinda tempted to remove that kivy example. I never updated it when I updated ffpyplayer and I just used it initially to test stuff manually so it's not surprising it's broekn. And ffpyplayer is completely separate from kivy so there's no reason to have a kivy example here.

If you want a kivy example, I'd suggest you look the ffpyplayer implementation in kivy - that is updated.

**Comment by kuzeyron** [comment]
Thank you. This example code (I believed)  was good because it have a few things that you have made that would have benefit my project so that's a `1+`.
